name: paek_cg 
channels:
  - conda-forge
dependencies:
  - freud
  - gsd
  - jupyter
  - matplotlib
  - numpy
  - pip
  - python=3.9
  - pytest
  - pytest-cov
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
